In [1]:
%reload_ext postcell
%postcell register

PostCell loaded
Loading config file from /Users/victorji/Documents/GitHub/lectures/postcell.conf
Registered user Victor_Ji at https://postcell.io/post_cell

In [2]:
import numpy as np
import pandas as pd

# Pandas - dataframes

Pandas dataframes are the main tool used by data scientists to explore data.Generally, "pandas" is a synonym for pandas dataframes. Pandas is deigned to work with what we normally think of as "business data."

Given what we have learned so far, we can think of dataframes as: Numpy with labels and a set of series objects.

#### Numpy with labels

In [3]:
rand_array = (np.random.rand(10,3) * 100).round()
rand_array

array([[93., 60., 50.],
       [11., 34., 98.],
       [17., 33., 16.],
       [74., 10., 20.],
       [ 2., 33.,  5.],
       [28., 32., 53.],
       [95., 69., 37.],
       [62., 58., 63.],
       [21., 55., 91.],
       [64., 53., 75.]])

With pandas, we can annotate this numeric matrix with labels:

In [4]:
student_scores_pd = pd.DataFrame(rand_array
             , columns=['Assignment 1', 'Assignment 2', 'Test']
             , index=['Homer', 'Marge', 'Bart', 'Lisa', 'Maggie', 'Jon', 'Arya', 'Ned', 'Danny', 'That red lady']
            )
student_scores_pd

               Assignment 1  Assignment 2  Test
Homer                  93.0          60.0  50.0
Marge                  11.0          34.0  98.0
Bart                   17.0          33.0  16.0
Lisa                   74.0          10.0  20.0
Maggie                  2.0          33.0   5.0
Jon                    28.0          32.0  53.0
Arya                   95.0          69.0  37.0
Ned                    62.0          58.0  63.0
Danny                  21.0          55.0  91.0
That red lady          64.0          53.0  75.0

A dataframe can be converted back to a numpy:

In [5]:
student_scores_pd.values

array([[93., 60., 50.],
       [11., 34., 98.],
       [17., 33., 16.],
       [74., 10., 20.],
       [ 2., 33.,  5.],
       [28., 32., 53.],
       [95., 69., 37.],
       [62., 58., 63.],
       [21., 55., 91.],
       [64., 53., 75.]])

In [6]:
student_scores_pd.to_numpy()

array([[93., 60., 50.],
       [11., 34., 98.],
       [17., 33., 16.],
       [74., 10., 20.],
       [ 2., 33.,  5.],
       [28., 32., 53.],
       [95., 69., 37.],
       [62., 58., 63.],
       [21., 55., 91.],
       [64., 53., 75.]])

#### Set of series objects

![](images/dataframes.jpg)

In [7]:
homers_grades = pd.Series(np.round(100 * np.random.rand(3)))
marges_grades = pd.Series(np.round(100 * np.random.rand(3)))
barts_grades = pd.Series(np.round(100 * np.random.rand(3)))
lisas_grades = pd.Series(np.round(100 * np.random.rand(3)))
maggies_grades = pd.Series(np.round(100 * np.random.rand(3)))
jons_grades = pd.Series(np.round(100 * np.random.rand(3)))
aryas_grades = pd.Series(np.round(100 * np.random.rand(3)))
neds_grades = pd.Series(np.round(100 * np.random.rand(3)))
dannys_grades = pd.Series(np.round(100 * np.random.rand(3)))
thatredlady_grades = pd.Series(np.round(100 * np.random.rand(3)))

In [8]:
homers_grades

0    53.0
1    48.0
2    58.0
dtype: float64

In [9]:
student_scores_pd = pd.DataFrame({
    'homer': homers_grades
    , 'marge': marges_grades
    , 'bart': barts_grades
    , 'lisa': lisas_grades
    , 'maggie': maggies_grades
    , 'jon': jons_grades
    , 'arya': aryas_grades
    , 'ned': neds_grades
    , 'danny': dannys_grades
    , 'That red lady': thatredlady_grades
})
student_scores_pd

   homer  marge  bart  lisa  maggie   jon  arya    ned  danny  That red lady
0   53.0   75.0  16.0  12.0    64.0   9.0  70.0   64.0   10.0           96.0
1   48.0   30.0   1.0  15.0    94.0  46.0  19.0  100.0   21.0           20.0
2   58.0   90.0   3.0  33.0    69.0  86.0  42.0   52.0   33.0           31.0

In [10]:
student_scores_pd = student_scores_pd.set_index(pd.Index(['Assignment 1', 'Assignment 2', 'Test']))
student_scores_pd

,homer,marge,bart,lisa,maggie,jon,arya,ned,danny,That red lady
Assignment 1,53.0,75.0,16.0,12.0,64.0,9.0,70.0,64.0,10.0,96.0
Assignment 2,48.0,30.0,1.0,15.0,94.0,46.0,19.0,100.0,21.0,20.0
Test,58.0,90.0,3.0,33.0,69.0,86.0,42.0,52.0,33.0,31.0

In [11]:
#student_scores_pd = student_scores_pd.set_index([['Assignment 1', 'Assignment 2', 'Test']])
#student_scores_pd

In [12]:
student_scores_pd = student_scores_pd.T
student_scores_pd

               Assignment 1  Assignment 2  Test
homer                  53.0          48.0  58.0
marge                  75.0          30.0  90.0
bart                   16.0           1.0   3.0
lisa                   12.0          15.0  33.0
maggie                 64.0          94.0  69.0
jon                     9.0          46.0  86.0
arya                   70.0          19.0  42.0
ned                    64.0         100.0  52.0
danny                  10.0          21.0  33.0
That red lady          96.0          20.0  31.0

Notice that while each series has its own index, in a dataframe, the index is shared among all columns.

In [13]:
student_scores_pd['Test']

homer            58.0
marge            90.0
bart              3.0
lisa             33.0
maggie           69.0
jon              86.0
arya             42.0
ned              52.0
danny            33.0
That red lady    31.0
Name: Test, dtype: float64

In [14]:
type(student_scores_pd['Test'])

pandas.core.series.Series

### Creating dataframes

Above we saw two examples of creating dataframes from dictionaries and numpy arrays. You are more likely to create dataframes by reading them from a data file or loading them from an sql server. The pandas overview already showed such an example but let's take a closer look at some important functions.

#### `.read_csv()`

Pandas provides a very useful way of ingesting csv (command delimited) files. These types of files are overwhelmingly the format used to distribute small and medium sized data.

In [15]:
data_df = pd.read_csv('../../datasets/deaths-in-gameofthrones/game-of-thrones-deaths-data.csv')

In [16]:
data_df.head()

,order,season,episode,character_killed,killer,method,method_cat,reason,location,allegiance,importance
0,1,1,1,Waymar Royce,White Walker,Ice sword,Blade,Unknown,Beyond the Wall,"House Royce, Night’s Watch",2.0
1,2,1,1,Gared,White Walker,Ice sword,Blade,Unknown,Beyond the Wall,Night’s Watch,2.0
2,3,1,1,Will,Ned Stark,Sword (Ice),Blade,Deserting the Night’s Watch,Winterfell,Night’s Watch,2.0
3,4,1,1,Stag,Direwolf,Direwolf teeth,Animal,Unknown,Winterfell,NaN,1.0
4,5,1,1,Direwolf,Stag,Antler,Animal,Unknown,Winterfell,NaN,1.0

Note that you can load a file directly from the web:

In [23]:
%%time
pd.read_csv('https://raw.githubusercontent.com/washingtonpost/data-game-of-thrones-deaths/master/game-of-thrones-deaths-data.csv').head()

CPU times: user 7.84 ms, sys: 2.6 ms, total: 10.4 ms
Wall time: 85 ms

,order,season,episode,character_killed,killer,method,method_cat,reason,location,allegiance,importance
0,1,1,1,Waymar Royce,White Walker,Ice sword,Blade,Unknown,Beyond the Wall,"House Royce, Night’s Watch",2.0
1,2,1,1,Gared,White Walker,Ice sword,Blade,Unknown,Beyond the Wall,Night’s Watch,2.0
2,3,1,1,Will,Ned Stark,Sword (Ice),Blade,Deserting the Night’s Watch,Winterfell,Night’s Watch,2.0
3,4,1,1,Stag,Direwolf,Direwolf teeth,Animal,Unknown,Winterfell,NaN,1.0
4,5,1,1,Direwolf,Stag,Antler,Animal,Unknown,Winterfell,NaN,1.0

In [18]:
#pd.read_excel()

The `.read_csv` function is very rich and lets you control:
1. Column names, including working with datasets which do not include column names: `names`, `header`
2. Which delimiter to use: comma, tabs, etc.: `delimiter`
3. Custom data types (in case your integers are being brought in as strings or floats): `dtype`
    a. `parse_dates` lets you control which columns are date or time values

etc.

Similarly `.read_sql` lets you read resutls of sql queries, `.read_feather` lets you read a very important upcoming format called `feather` or `arrow`. Popular format 'parquet' from the Hadoop ecosystem can be read with `.read_parquet`

An example of read_csv's richness:

`.read_csv(header=int or list of int)`
The option of `header` can be used to control the header.
    - `header = 0` The first row contains the header, use that for column names
    - `header = [0,1,2,3,10]` Only import columns 0, 1, 2, 3 and 10 (skip 4-9)
    - `header = None` No column names provided

#### `.read_html()`

The `read_html` function parses a web page to extract tables. This functionality is built on top of the "beautiful soup" library. Using that library is not necessarily easy for new developers. Along with Python, they also have to know a bit about the html markup langauge. Pandas makes such tasks trivial.

In [ ]:
import ssl
#In some instances, students get ssl errors, this will resolve it
#https://stackoverflow.com/a/56230607
ssl._create_default_https_context = ssl._create_unverified_context

SyntaxError: invalid syntax (1768310257.py, line 3)

In [28]:
%%time
html_tables = pd.read_html('https://en.wikipedia.org/wiki/World_population')

CPU times: user 3.56 ms, sys: 2.18 ms, total: 5.74 ms
Wall time: 153 ms

HTTPError: HTTP Error 403: Forbidden

In [22]:
len(html_tables)

NameError: name 'html_tables' is not defined

In [ ]:
html_tables[0]

In [ ]:
html_tables[1]

If you want a specific table, use the `match` keyword to search for a specific table header

In [ ]:
pd.read_html('https://en.wikipedia.org/wiki/World_population'
             , match='10 most densely populated countries')[0]

**Exercise** Download the following file to you computer and read it into a dataframe: https://raw.githubusercontent.com/codeforamerica/ohana-api/master/data/sample-csv/addresses.csv

Note, you must download the file to you computer, you may not use Pandas to read directly from the web.

In [ ]:
%%postcell exercise_030_120_a

#type your answer here

### Getting rows and columns from Dataframes

In [ ]:
student_scores_pd

Similar to series, values in dataframes can be retrieved in several ways:
1. Implicit index (similar to lists)
2. Explicit index or label (similar to dictionaries)
3. Slicing
4. Boolean masking
5. Fancy indexing

#### Implicit index

Perhaps surprisingly, implicit index is not commonly used to acces rows or columns (see `iloc` or `icol`)

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd[0]

In [ ]:
student_scores_pd.iloc[:, 0]

#### Explicit index or labels

In [ ]:
student_scores_pd

In a dataframe, using an explicit key returns the column associated with that key. Note that this is not what you may have expected. According to the rule "first rows, then column" we learned in numpy, the syntax in the following line should result a row, but Pandas makes an exception here.

In [ ]:
student_scores_pd['homer']

In [ ]:
student_scores_pd['Test']

Notice, in the last example, although, in common vernacular, you are asking for a column of data. It is more precise to say that you are asking for a series, since a series contains a column of values, and the index associated with it.

Using `.loc` brings back the "rows then column" scheme.

In [ ]:
student_scores_pd.loc['homer']

In [ ]:
student_scores_pd.loc[:, 'Test']

In [ ]:
student_scores_pd.loc['homer', "Test"]

Once you have a series, you can operate on it using the same methods we learned in the previous lecture

In [ ]:
tests_s = student_scores_pd['Test']

In [ ]:
type(tests_s)

In [ ]:
tests_s

In [ ]:
tests_s['homer'] # <= this is a series, not a dataframe

Dataframe and series operations are often combined

In [ ]:
student_scores_pd['Test']['homer']

In the pervious example, `student_scores_pd['Test']...` returns a series, the subsequent `...['homer']` then pulls out Homer's test results.

**Exercise** Find the average of all test scores in `student_scores_pd`

In [ ]:
%%postcell exercise_030_120_b

#type your answer here

#### Fancy indexing

Fnacy indexing operates on columns

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd[['Test', 'Test', 'Assignment 1']]

**Exercise** Get the `Test` series from `student_scores_pd`

In [ ]:
%%postcell exercise_030_120_c

#type your answer here

#### Slicing

However, if slicing syntax is used to operate on rows

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd['bart': 'arya']

**Note** Sclicing columns names will not work (unless the `.loc` notation is used)

In [ ]:
student_scores_pd['Assignment 1': 'Assignment 2']

In [ ]:
student_scores_pd.loc[:, 'Assignment 1': 'Assignment 2']

**Exrercise** Use slicing to find test scores (not assignments) for Maggie, Jon and Arya (note that all three are next to each ohter in the dataframe

In [ ]:
%%postcell exercise_030_120_d

#type your answer here

#### Masking

Masking syntax also operates on rows

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd[student_scores_pd.Test > 50]

In [ ]:
student_scores_pd.Test > 50

In [ ]:
student_scores_pd[student_scores_pd.index == 'homer']

**Exercise** Find all records where test scores are above 80 in dataframe `student_scores_pd`

In [29]:
%%postcell exercise_030_120_e

#type your answer here
scores_above_80 = student_scores_pd[student_scores_pd.Test > 80]
print(scores_above_80)

Cell posted for evaluation
       Assignment 1  Assignment 2  Test
marge          75.0          30.0  90.0
jon             9.0          46.0  86.0

**Exercise** Find all records where test scores are above 80 or assignment 1 scores are above 75 in dataframe `student_scores_pd`

In [31]:
%%postcell exercise_030_120_h

#type your answer here
scores_80_or_75 = student_scores_pd[(student_scores_pd.Test > 80) | (student_scores_pd['Assignment 1'] > 75)]
print(scores_80_or_75)

Cell posted for evaluation
               Assignment 1  Assignment 2  Test
marge                  75.0          30.0  90.0
jon                     9.0          46.0  86.0
That red lady          96.0          20.0  31.0

### `.loc`, `.iloc` and `.at`

Just like `Series`, `Dataframe` objects also use:

- `df.loc[]` to operate only on explicit keys/labels (like dictonaries)
- `df.iloc[]` to operate only on implicit index locations (like lists)
- `df.at[]` to return a single item

However, since Dataframes are a multidimensional data structure, these functions provide direct ability to access rows and columns

`df.loc/iloc/at[rows, columns]`

In [33]:
student_scores_pd

               Assignment 1  Assignment 2  Test
homer                  53.0          48.0  58.0
marge                  75.0          30.0  90.0
bart                   16.0           1.0   3.0
lisa                   12.0          15.0  33.0
maggie                 64.0          94.0  69.0
jon                     9.0          46.0  86.0
arya                   70.0          19.0  42.0
ned                    64.0         100.0  52.0
danny                  10.0          21.0  33.0
That red lady          96.0          20.0  31.0

### `.loc` key based indexing

Get the column 'Test' and all rows

In [34]:
student_scores_pd.loc[:,'Test']

homer            58.0
marge            90.0
bart              3.0
lisa             33.0
maggie           69.0
jon              86.0
arya             42.0
ned              52.0
danny            33.0
That red lady    31.0
Name: Test, dtype: float64

Get all columns for row containing 'homer'

In [35]:
student_scores_pd.loc['homer', :]

Assignment 1    53.0
Assignment 2    48.0
Test            58.0
Name: homer, dtype: float64

Get the column 'Test' and row with index 'homer'

In [36]:
student_scores_pd.loc['homer', 'Test']

np.float64(58.0)

Get columns 'Assignment 1' and 'Assignment 2' and rows containing Simpson children (**fancy indexing**)

In [ ]:
student_scores_pd.loc[['bart', 'lisa', 'maggie'],['Assignment 1', 'Assignment 2']]

Get 'Test' scores for everyone between 'bart' and 'maggie' (**slicing** and **fancy indexing**)

In [37]:
student_scores_pd.loc['bart':'maggie', ['Assignment 1', 'Assignment 2']]

        Assignment 1  Assignment 2
bart            16.0           1.0
lisa            12.0          15.0
maggie          64.0          94.0

**Exercise** Find Maggie and Danny's 'Assignment 1' score

In [ ]:
%%postcell exercise_030_120_f

#type your answer here

### .iloc location based indexing

In [ ]:
student_scores_pd

Get the first column and all rows

In [ ]:
student_scores_pd.iloc[:, 0]

Get the second column and 3-5 rows

In [ ]:
student_scores_pd.iloc[3:6, 1]

**Exercise** Get the first three rows of `student_scores_pd`, but only include 'Assignment 1' and 'Assignment 2'

In [ ]:
%%postcell exercise_030_120_g

#type your answer here

### `.at` return a single value

Get Homer's test results (think of it as `.loc` which returns a single value...or an error)

In [ ]:
student_scores_pd.at['homer', 'Test']

In [ ]:
student_scores_pd.at['homer',['Test', 'Assignment 1']]

#### `.query()`

Although I personally haven't developed a habit of using this function, `df.query(..)` can be very useful and intuitive

In [ ]:
student_scores_pd

In [ ]:
student_scores_pd.query('Test > 50')

The above example is the same as:

In [ ]:
student_scores_pd[student_scores_pd['Test'] > 50]

As you can see, `.query()` is much simpler